print("Hello may i know your name ??")
first_name = input("Enter first name:")
second_name = input("Enter Second name:")
surname = input("Enter Surname:")
print("Hi " + first_name + " " + second_name + " " + surname)
